HW18
AndriiKozlovets/proj-homeworks-kozlovets pull request #12
Opened 2023-10-06 16:36 UTC by AndriiKozlovets

2023-10-08 16:31 UTC, bielanm requested changes

2023-10-08 16:31 UTC, bielanm commented on HW18/testing.py
> +    def test_update(self):
В цьому тесті ще треба перевірити чи був викликаний метод print().
Можеш зробити два варіанти:

1. замокати сам print
2. підмінити sys.stdout за допомогою якогось io.StringIO

2023-10-13 07:54 UTC, AndriiKozlovets commented on HW18/testing.py
> +    def test_update(self):
поправив файл testing.py

2023-10-13 11:14 UTC, bielanm approved these changes

2023-10-13 11:18 UTC, merged