hw9
AndriiKozlovets/proj-homeworks-kozlovets pull request #3
Opened 2023-09-26 21:24 UTC by AndriiKozlovets

2023-10-07 14:19 UTC, bielanm requested changes
В корені проєкта створи файл `.gitignore` і туди запиши вміст з ось цього прикладу.
https://github.com/github/gitignore/blob/main/Python.gitignore.
Це вбереже тебе від комітів непотрібних файлів в надалі. Але так як ти вже закомітив `__pycache__`, то треба видалити її і зробити:
```
git add .
git commit --amend
```

2023-10-09 19:39 UTC, AndriiKozlovets commented
Щось тут наробив, не з першого разу, але вийшло.

2023-10-10 21:38 UTC, bielanm approved these changes

2023-10-10 21:38 UTC, bielanm commented
Замерж зі сквошем (якщо там є така опція).

2023-10-10 21:50 UTC, merged