hw11
AndriiKozlovets/proj-homeworks-kozlovets pull request #5
Opened 2023-09-26 21:48 UTC by AndriiKozlovets

2023-10-07 14:36 UTC, bielanm requested changes

2023-10-07 14:36 UTC, bielanm commented on HW11/HW11_telegram_bot.py
> +api_key = "lwZGuUKXitiTsBd4ppeWgcMpV5tTfV6Z"
Апі ключі неможна комітити у репозиторій, їх треба передавати через змінні оточення і вичитувати за допомогою `os.getenv`: https://www.twilio.com/blog/environment-variables-python

також зверни увагу, коли зміниш, то тобі треба буде також зробити коміт з амендом (як я писав в домашці 9), бо новий коміт залишить ключ в історії проєкту.

2023-10-09 21:14 UTC, AndriiKozlovets commented
Поправив, але вийшло зробити тільки з повним шляхом до файлу gifs.env з API ключами

2023-10-11 16:07 UTC, bielanm approved these changes

2023-10-12 07:28 UTC, merged