HW15
AndriiKozlovets/proj-homeworks-kozlovets pull request #9
Opened 2023-09-28 14:23 UTC by AndriiKozlovets

2023-10-08 15:30 UTC, bielanm requested changes
1. Ревʼю повинне бути привʼязаним до резервації, бо виходить що в тебе його може залишити будь хто, про будь кого: подумай також які звʼязки з тих що є зараз не/потрібні.
2. Додай також optional про оплату.

2023-10-10 16:02 UTC, AndriiKozlovets commented
поправив файл airbnb2.sql. 
1. У таблиці reviews виправив зв'язок з резервацією. прибрав лишні зв’язки.
2. Також у таблиці reservations прибрав зв'язок FOREIGN KEY (room_id) REFERENCES rooms(room_id), бо відношення між бронюванням та номером можна було встановити через гостя, який вибирав конкретний номер.
3. Додав таблицю payments.

2023-10-10 21:42 UTC, bielanm approved these changes

2023-10-10 21:43 UTC, bielanm requested changes

2023-10-10 21:43 UTC, bielanm commented on HW15/airbnb2.sql
> +    room_id INT,
Відношення для кімнати повинно залишитися

2023-10-12 10:56 UTC, AndriiKozlovets commented on HW15/airbnb2.sql
> +    room_id INT,
поправив

2023-10-12 11:19 UTC, bielanm approved these changes

2023-10-12 11:39 UTC, merged